task_finished
poemypoemy8/kintone_dojo pull request #1
Opened 2022-06-27 01:27 UTC by poemypoemy8

お疲れさまです！
こちらで課題が完了しました。

ご確認をよろしくお願いいたします🙇‍♀️

2022-06-27 05:40 UTC, saek-0 requested changes
Task1おつかれさま！
コメントしたので確認して再提出お願いします！
分からなかったらzoomつなげるので遠慮なく！

2022-06-27 05:40 UTC, saek-0 commented on task01/task1.html
> +      </div>
headerタグの中に、4製品の画像の要素が含まれています！
メインタグのところに記載しましょう。

2022-06-27 05:40 UTC, saek-0 commented on task01/task1.html
> +        <img src="img/image-kn.png">
画像の指定方法が間違っています
ヒント：相対パス

2022-06-27 05:40 UTC, saek-0 commented on task01/task1.html
> +      </div>
imgタグの中にも4製品共通のクラス名を追加して、
CSSで画像の部分を指定してあげてください。

2022-06-27 05:40 UTC, saek-0 commented on task01/task1.css
> +}
htmlでコメントした、imgタグのクラス名と、divのクラス名の役割を考えて、
記述を変更してみてください！

2022-06-27 09:39 UTC, poemypoemy8 commented on task01/task1.html
> +      </div>
main タグの中に移動させました！

2022-06-27 09:40 UTC, poemypoemy8 commented on task01/task1.html
> +        <img src="img/image-kn.png">
`./img/image-kn.png`
としました！

2022-06-27 09:41 UTC, poemypoemy8 commented
@saek-0 
レビューありがとうございました！
指摘いただいたところを修正したので、お手数ですが再度確認をよろしくお願いいたします…！

2022-06-28 13:47 UTC, saek-0 requested changes
修正ありがとう！もう少し。
コメントの確認お願いします！

2022-06-28 13:47 UTC, saek-0 commented on task01/task1.html
>        </div>
「kitnone dojo HTML/CSS課題」は「見出し(header)」に該当するので、
mainタグに含むのは正しくなさそうですね。headerタグの中に入れてあげてください！

2022-06-29 05:41 UTC, poemypoemy8 commented on task01/task1.html
>        </div>
@saek-0 
お疲れさまです。見逃していました💦 ありがとうございます！
こちら修正させていただきました。

2022-06-29 07:42 UTC, saek-0 commented on task01/task1.html
>        </div>
@poemypoemy8 
クラス名も一緒に移動してあげてください！

2022-06-30 03:06 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！たびたび確認ミス、お手数煩わせてしまいすみません💦
divについても移動させました。 よろしくお願いいたします。

2022-06-30 05:11 UTC, saek-0 approved these changes

2022-06-30 05:12 UTC, merged