Task03
poemypoemy8/kintone_dojo pull request #2
Opened 2022-06-30 03:08 UTC by poemypoemy8

@saek-0 
お疲れさまです！
task3の課題が終了しましたので、レビューのほどよろしくお願いいたします🙇‍♂️

2022-07-01 06:41 UTC, saek-0 requested changes
回答おつかれさま！
動いているから合ってはいるんだけど、もっと良い書き方ありそうだから細かめにコメントしています！

■task4-1
変数の定義方法についてと、===じゃなくて+=とかを使った方が全体がすっきりすると思いました。詳しくはコメントを確認ください。

■task4-2
task4-2も4-1と同じコメントになるので、わかりそうだったら一緒に修正して再提出してください！

2022-07-01 06:41 UTC, saek-0 commented on task03/task4-1.html
> +  const disc_btn = document.getElementsByClassName('chk')[1];  // チェックボックスの名前
この表現も正解だけど、
1行にまとめるほうがわかりやすいかな？
`const chkbox = document.getElementsByClassName('chk');`
にしておけば、
後にchkbox[0]とchkbox[1]で指定できるので全体を見た時にわかりやすくなると思います！

2022-07-01 06:41 UTC, saek-0 commented on task03/task4-1.html
> +      document.getElementById('price').textContent= calcPrice(0,0);
考え方はokだけど、もっと短く書く方法があります。
`===`を使うと、「両方のチェックが入っていた時に...」「入ってないときに...」とめんどくさいので、
代入演算子の`+=` `-=` を使う.....どうやって書けるでしょう？ (テキストP.28)
6行で書けます

ヒント：チェックが入っていたら、`price`にvalueの値を「加算して代入させる」

2022-07-01 06:41 UTC, saek-0 commented on task03/task4-1.html
> +      }
L60〜64
ここの変数の定義必要ですか？
L49〜50に、valueの値があるのでここで定義しなくてもデータの呼び出しができると思います。

2022-07-01 06:41 UTC, saek-0 commented on task03/task4-1.html
> +  disc_btn.onclick = () =>{
上記と一緒です！加算減算の代入演算子を使って記載してみましょう！

2022-07-01 06:41 UTC, saek-0 commented on task03/task4-2.html
> +  const discNum = document.getElementsByClassName('slct')[1];
ここも、task4-1と同様
配列名[インデックス番号]は後のコードで指定した方がわかりやすいです！
`const chkbox = document.getElementsByClassName('chk');`
`const select = document.getElementsByClassName('slct');`
にして、後のコードでchekbox[0]等で指定してあげる。

2022-07-04 06:28 UTC, poemypoemy8 commented on task03/task4-1.html
> +      }
> L60〜64 ここの変数の定義必要ですか？ L49〜50に、valueの値があるのでここで定義しなくてもデータの呼び出しができると思います。

こちらはおそらく変数定義のない形で書けたと思います！
確認をお願いいたします。

2022-07-04 06:33 UTC, poemypoemy8 commented on task03/task4-1.html
> +      document.getElementById('price').textContent= calcPrice(0,0);
`+=` を使う形での記述を考えてみました！
ひとまず「ボタンを押すと表示されている金額が増える」機能は実装しているように見える状態までにしました。

ただ「ボタンを押すと、その回数分だけ値段の数字が大きくなってしまう」「その状況の解消のために、onclick イベントの中で `price = 3900` （金額の初期化）を定義すると、両方のボタンが押されているときに数字がおかしくなってしまう」
の部分で悩んでおります…。

まだ完成でなく恐縮ですが、方向的にはこちらであっていそうでしょうか…！
よろしくお願いします🙇‍♀️

2022-07-04 06:34 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！お忙しいところレビューありがとうございます🙇‍♀️
いただいたコメントを基に、コードを再考しました。（いただいたコメントにリプライの形で考えをまとめております！）

よろしくお願いいたします。

2022-07-05 08:14 UTC, saek-0 commented on task03/task4-1.html
> +      document.getElementById('price').textContent= calcPrice(0,0);
@poemypoemy8 
>「ボタンを押すと、その回数分だけ値段の数字が大きくなってしまう」

ボタンが押されていない時の処理を書けば解決するはずです！
`-+`を使って処理を追記してみましょう。

2022-07-05 08:14 UTC, saek-0 commented on task03/task4-1.html
> +      }
ok!

2022-07-12 07:06 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！大変お時間いただきました。
github上のconflictを解消するために作り直したため、コードの差分が見えなくなってしまっているかもしれません…。
zoomでお話ししたときにアドバイスいただいた、「+や-の演算子を使う」方法でコードを書き直しました！

ご確認よろしくお願いいたします。

2022-07-12 07:39 UTC, saek-0 approved these changes
Okです！回答おつかれさま🌟

2022-07-12 07:39 UTC, merged