Mid task
poemypoemy8/kintone_dojo pull request #4
Opened 2022-07-12 07:15 UTC by poemypoemy8

@saek-0 
お疲れさまです！中間課題のコードです。
「余裕があれば取り組む」項目はskipして、ひとまず満たすべき条件のみ記述させていただきました。

ご確認よろしくお願いいたします🙇‍♀️

2022-07-13 02:51 UTC, saek-0 requested changes
一旦、以下のwatchdogにjs貼り付けてエラー文を見ながら正しいインデントに修正お願いします！
https://rybb.github.io/dojo-jswatchdog/

vscodeでは2マスなのに、gitにあげると4マスになってしまう場合は、
vscode側の設定がおかしい場合があります！ぐぐったら設定方法出てくると思うので確認お願いします！
レビューはそのあとしますね✨

2022-07-13 04:01 UTC, poemypoemy8 commented
@saek-0 
ありがとうございます！
他の課題でもそうですが、インデントのチェックができていませんでした💦

コードの表記法含めて訂正しましたので、確認よろしくお願いいたします！

2022-07-15 08:26 UTC, saek-0 requested changes
おつかれさま！
テーブルの記述間違ってはないんですが、だいぶ長いのですっきりさせましょう！
ヒントも記載したので、一旦考えてみてください✨
Dojo課題もあとちょっと、、がんばれ〜〜〜！！

2022-07-15 08:26 UTC, saek-0 commented on task05-mid/task5.js
> +        }
CSSの要素は、CSS要素に入れてあげたいですね

2022-07-15 08:26 UTC, saek-0 commented on task05-mid/task5.js
> +        document.getElementById((index) + '-' + 2).style.color = '#fff';
実はテーブルの作成はinnerHTMLを使うとコードを短縮できます。
変数で定義したhtml要素に、テーブル情報を加算代入してあげるイメージです。

ヒント：
①HTML上でベースのテーブルタグを作っているので、まず1個のニュース単位の枠組みを作る。
②作成したテーブルに、日付、カテゴリー名、タイトル情報を入れるタグを追加していく。

2022-07-22 06:14 UTC, poemypoemy8 commented
@saek-0 
おつかれさまです！大変お時間いただき失礼いたしました(´;ω;｀)
`innerHTML`を使ってテーブルの表現を書き直しました！
また、CSS要素についても指定自体はCSSファイル内で行って、クラスを付与する形で条件分岐させました。

ご確認よろしくお願いいたします🙇‍♀️

2022-07-22 07:21 UTC, saek-0 requested changes
修正おつかれさま！あとすこし....!

コメントの確認お願いします！

2022-07-22 07:21 UTC, saek-0 commented on task05-mid/task5.js
> +        tableData.innerHTML += `<td><a class = "content" link>${resp.data[index].content.value}</a></td>`;
13〜18行目まとめられるかもしれないです！
13行目で一旦row作成しているけど、結局取得してそのあとtdを入れ込んでるのであれば最初からtrの中にtd入れたHTMLをinnerHTMLに設定すれば良いと思います！
そして16〜18行目で毎回tableData.innerHTML +=してるけど、代入は1回でOKです。
（改行してOK）

そしてinnerHTMLしているのであればクラスの付与もHTML内に書き込んでしまえば簡潔になります。

2022-07-25 00:01 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！確認ありがとうございます🙇‍♀️
innerHTMLに全部入れてしまうのは思いつけていませんでした…！ 修正しましたのでレビューのほどお願いいたします！

2022-07-27 00:22 UTC, saek-0 approved these changes
LGTMです！㊗
おつかれさまでした！！

2022-07-27 00:22 UTC, merged