Task06
poemypoemy8/kintone_dojo pull request #5
Opened 2022-07-12 07:21 UTC by poemypoemy8

@saek-0 
お疲れさまです！
6-1.jsに関してはdevnetでほぼ答えに近い記事を見つけて参照しながら書いたため、
6-2.jsでは参照せず、自力で書き直しました。

お忙しいところ一気にリクエスト出してしまいご迷惑おかけします…。
よろしくお願いいたします。

2022-07-12 07:57 UTC, saek-0 requested changes
レビューしました！
6-2.jsだけにコメントしてるので確認&修正お願いします！
javascript講義で習ったことを応用して書けるはずです！

2022-07-12 07:57 UTC, saek-0 commented on task06/task6-2.js
> +        console.log(event);
console.logはデバッグ用なのでプルリクする際には削除しましょう！

2022-07-12 07:57 UTC, saek-0 commented on task06/task6-2.js
> +    'use strict';
全体的にインデントがおかしいので修正しましょう！

2022-07-12 07:57 UTC, saek-0 commented on task06/task6-2.js
> +            'value':{
まずはAction5を変数で定義して、配列をforEachで回してあげる方がすっきり書けると思います！

ヒント：
const action5 = ['あくなき探求', '不屈の心体', '理想への共感', '心を動かす', '知識を増やす', '公明正大'];
const newRow = [];
action5.forEach((val) => {
}

2022-07-13 03:26 UTC, poemypoemy8 commented
@saek-0 
おつかれさまです！
いただいたヒントをもとに記述を変更しました！

ご確認のほどお願いいたします🙇‍♀️

2022-07-13 04:09 UTC, saek-0 requested changes
スペースわすれないようにしましょう！

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +  const action5 = ['あくなき探求','不屈の心体','理想への共感','心を動かす','知識を増やす','公明正大'];
```suggestion
  const action5 = ['あくなき探求', '不屈の心体', '理想への共感', '心を動かす', '知識を増やす', '公明正大'];

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +  kintone.events.on('app.record.create.show',(event) =>{
```suggestion
  kintone.events.on('app.record.create.show', (event) => {

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +    action5.forEach((val,index)=>{
```suggestion
    action5.forEach((val, index) => {

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +      {
```suggestion
      newRow[index] = {

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +            'value':action5[index],
```suggestion
        'value': {
          'Action5': {
            'type': 'DROP_DOWN',
            'value': action5[index],

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +            'value':['未振り返り']
```suggestion
          '課題': {
            'type':' MULTI_LINE_TEXT',
            'value': '',
          },
          '状況': {
            'type': 'CHECK_BOX',
            'value': ['未振り返り']

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +      }
L25 missing ;
```suggestion
      } ;

```

2022-07-13 04:09 UTC, saek-0 commented on task06/task6-2.js
> +    })
```suggestion
    });

```

2022-07-13 05:13 UTC, poemypoemy8 commented
@saek-0 
jswatchdogで LGTM になるところまで調整しました！
お手数をおかけしました🙇‍♀️ ありがとうございます！

2022-07-14 01:53 UTC, saek-0 approved these changes
OKです！
ちなみに3,4行目の変数宣言はイベントの発生後にした方がいいですので、今後気をつけてみてください！

2022-07-14 01:53 UTC, merged