task07 first commit
poemypoemy8/kintone_dojo pull request #6
Opened 2022-07-12 07:39 UTC by poemypoemy8

@saek-0 
お疲れさまです！
一度に大量にプルリクエストをあげてしまい、失礼いたしました…。

こちらについてもご確認のほどよろしくお願いいたします🙇‍♀️

2022-07-14 02:13 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです。date-fnsライブラリを使ってコードをかけていなかったので修正します。
終わったらまたこちらにコメント残させていただきます！

2022-07-14 03:14 UTC, poemypoemy8 commented
@saek-0 
date-fnsを使った書き方に変更しました！ お手数をおかけしました。

2022-07-14 03:53 UTC, saek-0 requested changes
修正ありがとう！だいぶコンパクトなコードになりましたね！
コメントの確認お願いします！

2022-07-14 03:53 UTC, saek-0 commented on task07/task7.js
> +    const YYYYMMDD = year + month + date;
課題文に日付は`dataFns`を使用しましょう、とあったはずです。
dataFnsを使えば、一行で書けるはず

2022-07-14 03:53 UTC, saek-0 commented on task07/task7.js
> +    product = event.record.サイボウズ製品.value;
L15とL41のイベントをまとめられるとコード短くかけそうです！

ヒント：
kintone.events.on([
    'app.record.create.change.日付',
    'app.record.edit.change.日付',
    'app.record.create.change.サイボウズ製品',
    'app.record.edit.change.サイボウズ製品',
    'app.record.create.change.管理番号',
    'app.record.edit.change.管理番号',
  ], (event) => {

2022-07-14 05:49 UTC, poemypoemy8 commented on task07/task7.js
> +    product = event.record.サイボウズ製品.value;
@saek-0 
ありがとうございます！
イベントと処理をまとめて書き直しました。

ご確認お願いいたします。

2022-07-14 05:50 UTC, poemypoemy8 commented
@saek-0 
ありがとうございます！
イベントと処理をまとめて書き直しました。

ご確認よろしくお願いいたします。

2022-07-14 23:57 UTC, saek-0 requested changes
コメントの確認お願いします！

2022-07-14 23:57 UTC, saek-0 commented on task07/task7.js
> +    event.record.重複禁止項目_文字列.value = `${YYYYMMDD}-${product}-${number}`;
L11 この処理必要かな？
ここのイベントでは、シンプルにレコードが作成/編集された時に重複禁止項目を編集負荷にするって処理だけでokだと思います！

2022-07-14 23:57 UTC, saek-0 commented on task07/task7.js
> +  let number = ''; // 管理番号のグローバル変数
なるべくconst使いたいです！
L24〜26に含められると思うけどどうでしょう？

2022-07-15 05:04 UTC, poemypoemy8 commented on task07/task7.js
> +    event.record.重複禁止項目_文字列.value = `${YYYYMMDD}-${product}-${number}`;
@saek-0 
ありがとうございます！
課題に「文字列に挿入するタイミングはレコード新規作成時・編集時」とあったので、レコードを開いた瞬間に文字が入っている形を想定して自動計算フィールドと挙動ができるだけ似るように記述していました…。

2022-07-15 05:06 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！こちら修正させていただきました！
ご確認よろしくお願いいたします🙇‍♀️

2022-07-19 01:18 UTC, saek-0 approved these changes
LGTMです！簡潔なコードで良くなりましたね✨

2022-07-19 01:18 UTC, merged