Task08
poemypoemy8/kintone_dojo pull request #7
Opened 2022-07-14 08:40 UTC by poemypoemy8

@saek-0 
おつかれさまです！

task8の動作確認が完了しましたのでご確認よろしくお願いいたします🙇‍♀️

2022-07-15 00:09 UTC, saek-0 requested changes
全体的によく書けていて感心します✨
L14〜22はもうすこしコンパクトにかけると思うのでコメントの確認お願いします！

2022-07-15 00:09 UTC, saek-0 commented on task08/task8.js
> +      }).sort((a, b) => {
実は、sortメソッドは破壊的（直接操作してしまう）なので推奨はされていません。
参考：https://maasaablog.com/development/javascript/1171/

L14〜22は、
L24と似たように[]で作った配列にforEachで回してあげるのが良さそうです。

ヒント：
const action5 = [];
Object.keys(options).forEach((val) => {

};

2022-07-15 06:09 UTC, poemypoemy8 commented
@saek-0 
レビューありがとうございます🎉
配列に変換するところまではできそうなのですが、forEachをつかってindexの順番通りに並べ替える方法がどうしても考え付かず…！
先ほどのcommitで途中まで書いておりますが、可能であればもう少しヒントをもらってもよろしいでしょうか(´;ω;｀)

2022-07-15 06:47 UTC, saek-0 requested changes
考え方はあってますが、もっとシンプルに考えていいはず。
コメントの確認お願いします！

2022-07-15 06:47 UTC, saek-0 commented on task08/task8.js
> +      })
Object.keys(options).forEach((val) => {
        action5[options[val].index] = options[val].label;
      });

options[val].indexのときのoptions[val].labelをaction5へ入れたいので。
↑でいけないかな？

2022-07-15 06:47 UTC, saek-0 commented on task08/task8.js
> +      return event;
このreturn event;必要ですか？
あと、err文はエラーになったときのログみたいので、`console.log(err);`入れておいてもいい気がします！

2022-07-15 07:33 UTC, poemypoemy8 commented on task08/task8.js
> +      })
@saek-0 
配列の番号を指定する際に`options[val].index` を使う方法が思いついていませんでした…。

実現したいことベースでもう少し冷静に考えられたらよかったです。ありがとうございます！

2022-07-15 07:33 UTC, poemypoemy8 commented
@saek-0 
指摘いただいた部分について修正しました！
よろしくお願いいたします。

2022-07-15 07:35 UTC, poemypoemy8 commented on task08/task8.js
> +      return event;
devnetで参考にしていた記事が `.catch` にもreturn を入れていたので無思考で入れていました。
.catchに処理を `console.log`以外イベントに返す処理を書いていないので必要なさそうですね…。
ありがとうございます！

2022-07-19 01:19 UTC, saek-0 approved these changes
こちらもLGTMです！✨
あとちょっとがんばれ〜〜〜！！

2022-07-19 01:19 UTC, merged