Task09
poemypoemy8/kintone_dojo pull request #8
Opened 2022-07-15 07:39 UTC by poemypoemy8

@saek-0 

お疲れさまです。
お忙しいところたくさんやり取りしていただき本当にありがとうございます🙇‍♀️

task9は、もともと`forEach`で重複の判定処理を書くことを考えていましたが、
重複しているレコードが複数あった場合confirmウインドが複数回出てきてしまうため
breakが使えるようにfor文で記述しました。

今回もよろしくお願いいたします。

2022-07-20 11:26 UTC, saek-0 requested changes
コメントしました！レビューおそくなってしまい申し訳ないです！
確認お願いします！

2022-07-20 11:26 UTC, saek-0 commented on task09/task9.js
> +          if (resp.records[[i]].重複禁止項目.value === event.record.重複禁止項目.value) {
・編集の場合の重複しているかどうかの条件が resp.records[[i]].重複禁止項目.value === event.record.重複禁止項目.value だけだと不足してる（自身のレコードを除外する必要あり）
→レコード全部取得してある分処理すると効率良くないのでquery使って絞り込むようにしましょう

2022-07-20 11:26 UTC, saek-0 commented on task09/task9.js
> +            } else {
・for breakも無理くり処理から抜けるのはあまり好ましくない
→上記の件クリアすれば回す必要なくなります！！

2022-07-25 00:07 UTC, poemypoemy8 commented
@saek-0 
お疲れさまです！レビューありがとうございます🙇‍♂️

クエリを使った絞り込みに記述を変更しました！
特に`app.record.edit.submit`の時に、自身のレコード番号も重複と判定する仕様だったため、その状況を回避できるような絞り込みにしました。

ご確認よろしくお願いいたします！

2022-07-27 04:34 UTC, saek-0 approved these changes
LTGMです！🎉🎉

Dojoの課題おつかれまでした！(レビュー時間かかってしまってごめんね！
ぽえみーちゃんの自己解決力やちゃんと課題を理解してコードに落とし込む姿勢など、すごいな〜と思ってレビューしてました！
Dojoで学んだことは、どの部署行っても役に立つと思います🌟

残りの製品研修もその調子でがんばってください！🤩

2022-07-27 04:35 UTC, merged

2022-07-27 06:05 UTC, poemypoemy8 commented
@saek-0 
さえぽんさん、レビューいただきありがとうございました！
もくもく会でも考えを読み取って答えにならない範囲でヒントをくださったり、このコメントでも励ましの言葉を残しておいて下さったりして、いつも元気をいただきました(´;ω;｀)
時間は掛かってしまいましたが、とても学びのあるdojo期間でした！

これからもよろしくお願いします！改めて、ありがとうございました🤗